apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-srv
  namespace: web-srv
spec:
  selector:
    matchLabels:
      app: web-srv
  replicas: 3
  template: # template for the pods
    metadata:
      labels:
        app: web-srv
    spec:
      containers:
      - name: web-srv
        image: nettas/websrv:2.0
        ports:
          - name: http
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-srv
  namespace: web-srv

spec:
  selector:
    app: web-srv

  type: ClusterIP

  ports:
  - port: 80
    protocol: TCP
    targetPort: 80