kind: Namespace
apiVersion: v1
metadata:
#use your your f5 email before the @... Example 's-iannetta'
  name: s-iannetta
  labels:
    name: s-iannetta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
#reminder to use your namespace from above
  namespace: s-iannetta 
spec:
  selector:
    matchLabels:
      app: web-page
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: web-page
    spec:
      containers:
      - name: web-page
        image: nettas/websrv2:3.1
        ports:
          - name: http
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
#reminder to use your namespace from above
  namespace: s-iannetta

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: web-page

  type: ClusterIP

  ports:
  - port: 80
    protocol: TCP
    targetPort: 80