kind: Namespace
apiVersion: v1
metadata:
#replace CHANGE_ME with your variable example netta
  name: CHANGE_ME
  labels:
  #replace CHANGE_ME with same as above
    name: CHANGE_ME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
#reminder to use your namespace from above
  namespace: CHANGE_ME
spec:
  selector:
    matchLabels:
      app: web-page
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: web-page
    spec:
      containers:
      - name: web-page
        image: nettas/websrv2:3.1
        ports:
          - name: http
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
#reminder to use your namespace from above
  namespace: CHANGE_ME

spec:
  selector:
    app: web-page

  type: ClusterIP

  ports:
  - port: 80
    protocol: TCP
    targetPort: 80